class IconData{
    static getCategory(){
        return {
            "general":{text:"よく使うもの", barColor :"bar-green"},
            "unusual":{text:"たまに使うもの", barColor :"bar-green"},
            "adult":{text:"アダルト", barColor :"bar-red"},
        }
    }

    static GetEement(){
        return [
            {
                parentClass:"general",
                classname:"showroom",
                href:"https://www.showroom-live.com/follow", 
                img:"img/showroom.png"
            },
            {
                parentClass:"general",
                classname:"twitter",
                href:"https://twitter.com/?lang=ja",
                img:"img/twitter.png"
            },
            {
                parentClass:"general",
                classname:"instagram",
                href:"https://www.instagram.com/?hl=ja",
                img:"img/instagram.png"
            },

            {
                parentClass:"general",
                classname:"tiktok",
                href:"https://www.tiktok.com/",
                img:"img/tiktok.png"
            },
            {
                parentClass:"general",
                classname:"yahoo-mail",
                href:"https://mail.yahoo.co.jp/",
                img:"img/yahoo_mail.webp"
            },
            {
                parentClass:"general",
                classname:"g-mail",
                href:"https://mail.google.com/mail/u/0/#inbox",
                img:"img/gmail.png"
            },
            {
                parentClass:"general",
                classname:"jra",
                href:"http://www.jra.go.jp/",
                img:"img/jra.png"
            },
            
            {
                parentClass:"general",
                classname:"dynalist",
                href:"https://dynalist.io/",
                img:"img/dynalist.png"
            },
            {
                parentClass:"general",
                classname:"qiita",
                href:"https://qiita.com/Stchan",
                img:"img/qiita.png"
            },
            {
                parentClass:"general",
                classname:"youtube",
                href:"https://www.youtube.com/",
                img:"img/youtube.webp"
            },
            {
                parentClass:"general",
                classname:"netflix",
                href:"https://www.netflix.com/browse",
                img:"img/netflix.png"
            },
            {
                parentClass:"general",
                classname:"amazon",
                href:"https://www.amazon.co.jp/",
                img:"img/amazon.png"
            },
            {
                parentClass:"general",
                classname:"nitori",
                href:"https://www.nitori-net.jp/ec/",
                img:"img/nitori.png"
            },
            {
                parentClass:"general",
                classname:"cainz",
                href:"https://www.cainz.com/",
                img:"img/cainz.jpg"
            },
            {
                parentClass:"general",
                classname:"hotpepper",
                href:"https://beauty.hotpepper.jp/CSP/my/bookmarkSalon/list/",
                img:"img/hotpepper.png"
            },
            {
                parentClass:"general",
                classname:"mixhost",
                href:"https://accounts.mixhost.jp/",
                img:"img/mixhost.jpg"
            },
            {
                parentClass:"general",
                classname:"muumuu-domain",
                href:"https://muumuu-domain.com/",
                img:"img/muumuu-domain.jpg"},
            {
                parentClass:"general",
                classname:"github",
                href:"https://github.com/",
                img:"img/github.png"
            },
            {
                parentClass:"general",
                classname:"cara-bar",
                href:"https://www.pokepara.jp/aichi/m201/a208/shop14450/",
                img:"img/cara-bar.png"
            },
            
            // new
            {
                parentClass:"general",
                classname:"web-extention",
                href:"https://addon.stchan130.com/",
                // img:"img/web_extention.png"
                img:"img/web_extention.svg"
            },

            {
                parentClass:"unusual",
                classname:"salary",
                href:"https://c01-sss03.kitora.toyota.co.jp/hpmex/servlet/RC",
                img:"img/salary.png"
            },
            {
                parentClass:"unusual",
                classname:"insurance",
                href:"https://tfweb94.jp/tmckenpo/servlet/RC",
                img:"img/insurance.png"
            },
            {
                parentClass:"unusual",
                classname:"yahoo-train", 
                href:"https://transit.yahoo.co.jp/",
                img:"img/yahoo_train.webp"
            },
            {
                parentClass:"unusual", 
                classname:"mufg",
                href:"http://www.bk.mufg.jp/",
                img:"img/mufg.gif"
            },
            {
                parentClass:"unusual", 
                classname:"mizuho",
                href:"https://www.mizuhobank.co.jp/index.html",
                img:"img/mizuho.png"
            },
            {
                parentClass:"unusual", 
                classname:"smbc",
                href:"https://www.smbc.co.jp/",
                img:"img/smbc.png"
            },
            {
                parentClass:"unusual",
                classname:"rakuten", 
                href:"https://www.rakuten-card.co.jp/e-navi/",
                img:"img/rakuten.png"
            },
            {
                parentClass:"unusual",
                classname:"jcb",  
                href:"https://my.jcb.co.jp/Login",
                img:"img/jcb.gif"
            },
            {
                parentClass:"unusual", 
                classname:"hawks", 
                href:"http://www.softbankhawks.co.jp/",
                img:"img/Softbank_hawks_logo.jpg"
            },
            {
                parentClass:"unusual", 
                classname:"library", 
                href:"https://www.library.toyota.aichi.jp/licsxp-opac/WOpacMnuTopInitAction.do?WebLinkFlag=1&moveToGamenId=tifschcmpd",
                img:"img/library.jpg"
            },
            {
                parentClass:"unusual",
                classname:"suumo", 
                href:"https://suumo.jp/jj/chintai/ichiran/FR301FC001/?ar=050&bs=040&smk=r01&ta=23&sc=23211&oz=23211015&oz=23211047&oz=23211058&oz=23211060&oz=23211065&oz=23211078&oz=23211081&oz=23211082&oz=23211101&oz=23211103&oz=23211124&oz=23211148&oz=23211165&oz=23211194&oz=23211244&oz=23211246&oz=23211260&cb=0.0&ct=9999999&mb=0&mt=9999999&md=02&md=03&et=9999999&cn=9999999&sngz=&po1=15",
                img:"img/suumo.jpg"
            },
        
            {
                parentClass:"adult",
                classname:"cityheaven", 
                href:"https://www.cityheaven.net/t/community/ABFavoriteGirlList/",
                img:"img/cityheaven.png"
            },
            {
                parentClass:"adult", 
                classname:"love-express",
                href:"https://n.ai2006.jp/top",
                img:"img/love_express.png"
            },
            {
                parentClass:"adult", 
                classname:"hostlove",
                href:"https://tokai.hostlove.com/tk_fupa/1?target=ita&str=%83%8F%83%93%83J%83%89%83b%83g",
                img:"img/hostlove.jpg"
            },
            {
                parentClass:"adult", 
                classname:"avhub",
                href:"https://local-avhub.com/",
                img:"img/local_avhub.png"
            },
            {
                parentClass:"adult",
                classname:"fanza", 
                href:"https://www.dmm.co.jp/digital/",
                img:"img/fanza.png"
            },
            {
                parentClass:"adult", 
                classname:"mgs",
                href:"https://www.mgstage.com/",
                img:"img/mgs.png"
            },
            {
                parentClass:"adult",
                classname:"geo", 
                href:"http://rental.geo-online.co.jp/adult/",
                img:"img/geo.jpg"
            },
            {
                parentClass:"adult", 
                classname:"sokmil",
                href:"http://www.sokmil.com/av/",
                img:"img/sokmil.png"
            },
            {
                parentClass:"adult",
                classname:"fc2", 
                href:"https://adult.contents.fc2.com/consumer/",
                img:"img/fc2.png"
            },
            {
                parentClass:"adult",
                classname:"myfans", 
                href:"https://myfans.jp/HAMEMI",
                img:"img/myfans.png"
            },
            {
                parentClass:"adult",
                classname:"duga", 
                href:"http://duga.jp/",
                img:"img/duga.png"},
            {
                parentClass:"adult",
                classname:"ave", 
                href:"https://www.aventertainments.com/",
                img:"img/ave.png"
            },
            {
                parentClass:"adult", 
                classname:"tsutaya",
                href:"https://movie.tsutaya-adult.com/netdvd/adl/top.do",
                img:"img/tsutaya.png"
            },
            {
                parentClass:"adult",
                classname:"sougouwiki", 
                href:"https://seesaawiki.jp/w/sougouwiki/",
                img:"img/amateur_av.png"
            },
            {
                parentClass:"adult",
                classname:"seesaawiki-av-neme",
                href:"https://seesaawiki.jp/av_neme/d/",
                img:"img/teach_actress.png"
            },
            {
                parentClass:"adult", 
                classname:"nkikaku",
                href:"https://www.nkikaku.jp/b/av1.htm",
                img:"img/nakamura-kikaku.png"
            },
            {
                parentClass:"adult",
                classname:"arzon", 
                href:"http://www.arzon.jp/",
                img:"img/arzon.png"
            },
            {
                parentClass:"adult",
                classname:"pureadult", 
                href:"http://pureadult.co.jp/",
                img:"img/otakara.png"
            },
            {
                parentClass:"adult", 
                classname:"suruga-ya",
                href:"http://www.suruga-ya.jp/",
                img:"img/surugaya.png"
            },
            {
                parentClass:"adult", 
                classname:"yahoo-auctions",
                href:"https://auctions.yahoo.co.jp/",
                img:"img/yahoo_ocu.jpg"
            },
        ]
    }
}
